criado edicao e cadastrar do perfil de candidato
zegotta-team/mais1code-2401 pull request #125
Opened 2024-07-11 04:28 UTC by DouglasB2022

criado edicao e cadastrar do perfil de candidato

2024-07-11 04:39 UTC, zegotta requested changes

2024-07-11 04:39 UTC, zegotta commented on web/controllers/CandidatoController.php
> +        session_start();
trocar pela função que já verifica se existe um candidato Logado.

`CandidatoController::exigeSessao();`

2024-07-11 04:39 UTC, zegotta commented on web/controllers/CandidatoController.php
> +        session_start();
trocar pela função que já verifica se existe um candidato Logado.

`CandidatoController::exigeSessao();`

2024-07-11 04:39 UTC, zegotta commented on web/controllers/CandidatoController.php
> +        $candidato = $_SESSION['candidato'];
Resgate o candidato atraves do DTO, pra garantir que está trabalhando com a informação mais atual.

A informação na sessão ja pode ter sido alterada no banco e só será atualizada na sessão no proximo login 

trocar pela função que já verifica se existe um candidato Logado.

`CandidatoDTO::recuperar($_SESSION['candidato']->getId());`

2024-07-11 04:39 UTC, zegotta commented on web/layouts/sistema-candidato/cabecalho.phtml
> +                <li class="nav-item dropdown">
Não teremos "cadastrar/editar"
O formulário é um só. 

Crie o menu "Meu perfil" dentro do menu "Minha conta" apontando para "candidato/perfil"

2024-07-11 04:39 UTC, zegotta commented on web/controllers/CandidatoController.php
> +    public function editar()
Não teremos uma action editar.
Teremos somente a perfil.
ela carrega o candidato e manda pra view

2024-07-11 04:39 UTC, zegotta commented on web/controllers/CandidatoController.php
> +
Resgate o candidato atraves do DTO, pra garantir que está trabalhando com a informação mais atual.

A informação na sessão ja pode ter sido alterada no banco e só será atualizada na sessão no proximo login

trocar pela função que já verifica se existe um candidato Logado.

`CandidatoDTO::recuperar($_SESSION['candidato']->getId());`

Mande essa info pra view saber como preencher os campos

2024-07-12 00:07 UTC, DouglasB2022 commented on web/controllers/CandidatoController.php
> +        session_start();
resolvido

2024-07-12 00:07 UTC, DouglasB2022 commented on web/controllers/CandidatoController.php
> +        $candidato = $_SESSION['candidato'];
resolvido

2024-07-12 00:07 UTC, DouglasB2022 commented on web/layouts/sistema-candidato/cabecalho.phtml
> +                <li class="nav-item dropdown">
resolvido

2024-07-12 00:08 UTC, DouglasB2022 commented on web/controllers/CandidatoController.php
> +        session_start();
resolvido

2024-07-12 00:08 UTC, DouglasB2022 commented on web/controllers/CandidatoController.php
> +    public function editar()
resolvido

2024-07-12 00:08 UTC, DouglasB2022 commented on web/controllers/CandidatoController.php
> +
resolvido

2024-07-12 00:24 UTC, zegotta approved these changes

2024-07-12 00:24 UTC, merged