criação da persistência filial
zegotta-team/mais1code-2401 pull request #67
Opened 2024-06-30 21:22 UTC by KauanNasciment0

criação da persistência filial

2024-06-30 21:37 UTC, zegotta requested changes

2024-06-30 21:37 UTC, zegotta commented on misc/ddl.sql
> +    logadouro   TEXT,
erro de grafia
log**r**adouro

2024-06-30 23:39 UTC, KauanNasciment0 commented on misc/ddl.sql
> +    logadouro   TEXT,
Resolvido

2024-07-01 01:45 UTC, zegotta approved these changes

2024-07-01 01:46 UTC, merged